final_project/final_project/urls.py
from django.contrib import admin
from django.urls import path , include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("marketer.urls"))
]

final_project/marketer/urls.py
from django.urls import path
from . import views

app_name = "marketer"

urlpatterns = [
    path("home/", views.return_home, name="home"),
    path("registration/", views.register, name="registration"),
    path("login/", views.login_user, name="login"),
    path("add-request/", views.add_markting_request, name="add-request"),
    path("all-requests/", views.list_chances, name="all-requests"),
    path("request_detail/<request_id>/", views.request_detail, name="request_detail"),
    path("request_detail/<request_id>/comment", views.add_comment, name="add_comment"),
    path("contact/", views.index, name="contact"),
     ] 

final_project/marketer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from taggit.managers import TaggableManager

# Create your models here.



class Request (models.Model):
    title = models.CharField(max_length=1024)
    name = models.CharField(max_length=1024)
    description = models.TextField()
    #publish_date = models.DateTimeField()
    #is_closed = models.BooleanField()
    image = models.ImageField(upload_to="images/")




class Offer(models.Model):
  requestt = models.ForeignKey(Request, on_delete = models.CASCADE) 
  name = models.CharField(max_length=256)
  content = models.TextField()
 # created_at = models.DateTimeField(auto_now=True)
  #amount = models.CharField(max_length=256)





#creating a profile for the user
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key=True)
    age = models.IntegerField()
    address = models.CharField(max_length=2048)


class Contact (models.Model):

  name = models.CharField(max_length=256)
  email = models.CharField(max_length=256)
  subject = models.CharField(max_length=650)
  message = models.CharField(max_length=1000)


class Tag(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

   

final_project/marketer/forms.py
from django import forms


class contactForm(forms.Form):
  name = forms.CharField(max_length=255)
  email = forms.EmailField()
  subject= forms.CharField(max_length=255)
  message= forms.CharField(widget=forms.Textarea)

final_project/marketer/views.py
from .forms import contactForm
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.contrib.auth.models import User
from .models import Request, Offer, Contact
from django.core.mail import send_mail
from django.template.loader import render_to_string






def index(request): 
    form_class = contactForm
    form = form_class(request.POST or None)
    if request.method == 'POST':
      
      if form.is_valid():
            email = form.cleaned_data['email']
            name = form.cleaned_data['name']
            message = form.cleaned_data['message']
            subject = form.cleaned_data['subject']

            html = render_to_string('home.html',{
              'name' : name,
              'email' : email ,
              'subject' : subject, 
              'message' : message   })
              
            send_mail('the contact from subject' , 'This is the message' , 'malsuhaim@outlook.sa',['malsuhaim@outlook.sa'], html_message=html )

            return redirect ('contact')
    else:
        form = contactForm()

    return render (request, 'contact.html', { 'form' : form })

def return_home (request : HttpRequest):


  return render(request, "home.html")

#registration 
def register (request : HttpRequest):
      
      if request.method == "POST":
        #creating the user
        new_user = User.objects.create_user(username=request.POST["username"], email= request.POST["email"],  password=request.POST["password"])
        new_user.save()
        return redirect("marketer:login")


        #creating the profile
        #user_profile = Profile(user=new_user, age=request.POST["age"], address=request.POST["address"])
        #user_profile.save()
      return render(request, "registration.html")

#login 
def login_user (request : HttpRequest):
  msg = ""
  if request.method == "POST":
        user = authenticate(request, username=request.POST["username"], password=request.POST["password"])
        
        if user:
            login(request, user)
            return redirect("marketer:home")
        else:
            msg = "User Not Found , check your credentials"

  return render(request, "login.html", {"msg" : msg})



def list_chances (request : HttpRequest):

    req = Request.objects.all().order_by("name") #to order by name
    return render(request, "all-requests.html", {"req" : req})



def add_markting_request(request : HttpRequest):

    user : User = request.user
    msg = ""

    if not (user.is_authenticated):
       return redirect("marketer:home")
    elif  request.method == "POST":
      new_request = Request (title=request.POST["title"], name = request.POST["name"], description = request.POST["description"] )
      msg = "Request has been sent successfully"
      new_request.save()
      #return redirect("marketer:home")
      

    return render(request, "add-request.html" , {"msg" : msg}  )
    
def request_detail (request : HttpRequest, request_id : int):
    try:
        req = Request.objects.get(id=request_id)
        offers = Offer.objects.filter(requestt = req)
    except:
       return render(request , "not_found.html")

    return render(request, "request_detail.html", {"req" : req ,"offers" : offers }) # , 


def add_comment(request: HttpRequest, request_id:int):
    
    requestt = Request.objects.get(id=request_id)

    if request.method == "POST":
        new_comment = Offer(requestt=requestt, name = request.POST["name"], content=request.POST["content"])
        new_comment.save()

    
    return redirect("all_request.html", requestt.id)

def search(request: HttpRequest):
    
    
    if "search" in request.GET:
        posts = Request.objects.filter(title__contains=request.GET["search"])
    else:
        posts = Request.objects.all()

    return render(request, "all-requests.html", {"posts" : posts})


# contact us 

def contact_us (request : HttpRequest):
    
  if request.method == "POST":
      new_contact = Contact (name=request.POST["name"], email = request.POST["email"], subject = request.POST["subject"], message = request.POST["message"] )
      new_contact.save()
     # return redirect("marketer:contact")
      msg = " thank you ! your email has been sent"

  return render( request, "contact.html", {"msg" : msg})

final_project/marketer/templates/add-request.html
{% extends "base.html" %}

{% block content  %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
	<div class="row">
	    
	    <div class="col-md-8 col-md-offset-2">
	        
    		<h1>Create Markting Request</h1>
    		
    		<form action="{% url 'marketer:add-request' %}" method="POST">
				{% csrf_token %}
    		    <strong class="">{{ msg }}</strong>
				
    		    <div class="form-group has-error">
    		        <label for="slug">Name <span class="require">*</span> </label>
    		        <input type="text" class="form-control" name="name" />
    		        
    		    </div>
    		    
    		    <div class="form-group">
    		        <label for="title">Type the title of your request  <span class="require">*</span></label>
    		        <input type="text" class="form-control" name="title" />
    		    </div>


    		    
    		    <div class="form-group">
    		        <label for="description">Description your request </label>
    		        <textarea rows="5" class="form-control" name="description" ></textarea>
    		    </div>
    		    
				<div class="form-group">
					<label  class="form-label">Post Image</label>
					<input type="file" name="image" accept="image/*" class="form-control" />

				</div>



    		    <div class="form-group">
    		        <p><span class="require">*</span> - required fields</p>
    		    </div>
    		    
    		    <div class="form-group">
    		        <button type="submit" class="btn btn-primary">
    		            Create
    		        </button>
    		        <button class="btn btn-default" href="{% url 'marketer:home' %}">
    		            Cancel
    		        </button>
    		    </div>
    		    
    		</form>
		</div>
		
	</div>
</div>

</br>
{% endblock %}

final_project/marketer/templates/all-requests.html
{% extends "base.html" %}

{% block content  %}
<section>
<div class="container">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
        </tr>
        </thead>
        <tbody>
            {% for req in req %}
            <tr>
                <th scope="row"><a href="{% url 'marketer:request_detail' req.id %}">{{ req.title }}</a></th>
                <td>{{ req.name }}</td>
                <td>{{ req.description }}</td>
                <td>


                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>
</section>

{% endblock %}

final_project/marketer/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Marketer </title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center  header-transparent ">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <h1><a href="{% url 'marketer:home' %}">Tswaiq</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>
      
      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'marketer:home' %}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'marketer:home' %}">About</a></li>
          <li><a class="nav-link scrollto" href="{% url 'marketer:login' %}">Login</a></li>
          <!--<li><a class="nav-link scrollto " href="#portfolio">Portfolio</a></li>-->
          <!--<li><a class="nav-link scrollto" href="#team">Team</a></li>-->
          <li class="dropdown"><a href="{% url 'marketer:all-requests' %}"><span>Opportunities</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="{% url 'marketer:add-request' %}"> create a new marketing request</a></li>
              <li class="dropdown"><a href="{% url 'marketer:all-requests' %}"><span>Current Opportunities </span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="{% url 'marketer:all-requests' %}"> current open request</a></li>
                  <li><a href="#">The closed requests</a></li>

                </ul>
 
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex flex-column justify-content-end align-items-center">
    <div id="heroCarousel" data-bs-interval="5000" class="container carousel carousel-fade" data-bs-ride="carousel">

      <!-- Slide 1 -->
      <div class="carousel-item active">
        <div class="carousel-container">
          <h2 class="animate__animated animate__fadeInDown">Welcome to <span>Tasweeq</span></h2>
          <p class="animate__animated fanimate__adeInUp">This platform aims to help the product owners and link them with professional marketers.</p>
          <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Read More</a>
        </div>
      </div>

      <!-- Slide 2 -->
      <div class="carousel-item">
        <div class="carousel-container">
          <h2 class="animate__animated animate__fadeInDown">Tswaiq</h2>
          <p class="animate__animated animate__fadeInUp">Tsweeq aims marketers to find work opportunities.</p>
          <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Read More</a>
        </div>
      </div>

      <!-- Slide 3 -->
      <div class="carousel-item">
        <div class="carousel-container">
          <h2 class="animate__animated animate__fadeInDown">find the last Opportunities</h2>
          <p class="animate__animated animate__fadeInUp">click here to see the last marketing requests.</p>
          <a href="{% url 'marketer:all-requests' %}" class="btn-get-started animate__animated animate__fadeInUp scrollto">Click Here</a>
        </div>
      </div>

      <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon bx bx-chevron-left" aria-hidden="true"></span>
      </a>

      <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon bx bx-chevron-right" aria-hidden="true"></span>
      </a>

    </div>

    <svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28 " preserveAspectRatio="none">
      <defs>
        <path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z">
      </defs>
      <g class="wave1">
        <use xlink:href="#wave-path" x="50" y="3" fill="rgba(255,255,255, .1)">
      </g>
      <g class="wave2">
        <use xlink:href="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)">
      </g>
      <g class="wave3">
        <use xlink:href="#wave-path" x="50" y="9" fill="#fff">
      </g>
    </svg>

  </section><!-- End Hero -->
  

  <main id="main">

    {% block content %}
    






  

   

    {% endblock %}
</main>


    
 

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>Tswaiq</h3>
      <p>“Marketing is the science and art of exploring, creating, and delivering value to satisfy the needs of a target market at a profit” (Kotler, 2001-2012).</p>
      <div class="social-links">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>Tswaiq</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js'%}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js'%}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

final_project/marketer/templates/contact.html
{% extends "base.html" %}

{% block content  %}

        <div>{{form.as_p}}</div>
        <button>submit</button>


{% endblock %}

final_project/marketer/templates/home.html
{% extends "index.html" %}

final_project/marketer/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block content  %}


<section class="vh-100">
    <div class="container-fluid h-custom">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-9 col-lg-6 col-xl-5">
          <img src="{% static 'img/testimonials/logo.png'%}"
            class="img-fluid" alt="Sample image">
        </div>
        <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
          <form action="{% url 'marketer:login' %}" method="POST">
            {% csrf_token %}

            <strong class="">{{ msg }}</strong>
  
            <div class="divider d-flex align-items-center my-4">
              <p class="text-center fw-bold mx-3 mb-0">login</p>
            </div>
  
            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="username" id="form3Example3" class="form-control form-control-lg" name="username"
                placeholder="Enter a valid email address" />
              <label class="form-label" for="form3Example3">User Name</label>
            </div>
  
            <!-- Password input -->
            <div class="form-outline mb-3">
              <input type="password" id="form3Example4" class="form-control form-control-lg"
                placeholder="Enter password" name="password" />
              <label class="form-label" for="form3Example4">Password</label>
            </div>
  
            <div class="d-flex justify-content-between align-items-center">
              <!-- Checkbox 
              <div class="form-check mb-0">
                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
                <label class="form-check-label" for="form2Example3">
                  Remember me
                </label>
              </div>
              <a href="#!" class="text-body">Forgot password?</a>
            </div> -->
  
            <div class="text-center text-lg-start mt-4 pt-2">
              <button type="submit" class="btn btn-primary btn-lg"
                style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
              <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href= "{% url 'marketer:registration' %}"
                  class="link-danger">Register</a></p>
            </div>
  
          </form>
        </div>
      </div>
    </div>
    
      <!-- Right -->
      <div>
        <a href="#!" class="text-white me-4">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="#!" class="text-white me-4">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="#!" class="text-white me-4">
          <i class="fab fa-google"></i>
        </a>
        <a href="#!" class="text-white">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </div>
      <!-- Right -->
    </div>
  </section>

  
  {% endblock %}

final_project/marketer/templates/not_found.html
{% extends "base.html" %}

{% block content  %}

<strong>this page not found</strong>


{% endblock %}

final_project/marketer/templates/registration.html
{% extends "base.html" %}
{% load static %}
{% block content  %}

<section class="vh-200" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
  
                  <form action="{% url 'marketer:registration' %}" method="POST" class="mx-1 mx-md-4">
                    {% csrf_token %}
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="text" id="form3Example1c" class="form-control" name="username" />
                        <label class="form-label" for="form3Example1c">Your Name</label>
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="email" id="form3Example3c" class="form-control" name="email"/>
                        <label class="form-label" for="form3Example3c">Your Email</label>
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="password" id="form3Example4c" class="form-control" name="password" />
                        <label class="form-label" for="form3Example4c">Password</label>
                      </div>
                    </div>
  
  
                    <div class="form-check d-flex justify-content-center mb-5">
                      <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3c" />
                      <label class="form-check-label" for="form2Example3">
                        I agree all statements in <a href="#!">Terms of service</a>
                      </label>
                    </div>
  
                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <button type="submit" class="btn btn-primary btn-lg" >Register</button>
                    </div>
  
                  </form>
  
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
  
                  <img src="{% static 'img/testimonials/logo.png'%}"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

</br>


  {% endblock %}

final_project/marketer/templates/request_detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}

    
        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{ req.title }}</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">posted by {{req.user}}</div>
                            <!-- Post categories-->
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src="{% static 'img/testimonials/default.jpg'%}" alt="..." /></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <h2 class="fw-bolder mb-4 mt-5">{{ req.name }}</h2>
                            <p class="fs-5 mb-4">{{ req.description }}.</p>
                            <!--<p class="fs-5 mb-4">{{ req.image }}.</p>-->
                        </section>
                    </article>
                    <!-- Comments section-->
                    <section class="mb-5">
                        <div class="form-group card bg-light">
                            <div class="form-group card-body">
                                <h2>Add your comment</h2>
                                <!-- Comment form-->
                                <form class=" form-group mb-4" action="{% url 'marketer:add_comment' req.id %}" method="POST">
                                    {% csrf_token %}
                                <div class="form-group">
                                <label class="form-label">Your Name:</label>
                                <input type="text" name="name" class="form-control" /> </div>
                                
                                <div class="form-group">   
                                <label class="form-label">Your Comment:</label>                             
                                <textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!" name="content"></textarea>
                                <input type="submit" class="btn btn-primary mt-2" value="New Comment" ></div></form>
                                <!-- Comment with nested comments-->
                                <h2>Comments</h2>
                                <div class="d-flex mb-4">
                                    
                                    <!-- Parent comment-->
                                    <div class="ms-3">
                                        
                                            {% for offer in offers %}
                                        <div class="form-group border rounded p-3 mt-3">
                                            <div class="fw-bold">Commenter Name</div>
                                            <h5>{{ offer.name }}</h5>
                                            <div class="fw-bold">Comment</div>
                                            <p>{{ offer.content }}</p>
                                            <span>{{ comment.created_at }}</span>
                                        </div>
                                    {% endfor %}
                                        

















                                       
                                                  

                                </div>
                                
                             </div>
                        </div>
                    </section>

                    
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                            <div>
                            {% if "search"  in  request.GET %}
                            <h2> Search results for "{{ request.GET.search }}": </h2>
                            {% endif %}
                            </div>



                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">similar opportunities</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="{% url 'marketer:all-requests' %}">opportunities</a></li>

                                    </ul>
                                </div>

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

       


            <!--{% for offer in offer %}
                <div class="border rounded p-3 mt-3">
                    <h5>{{ offer.name }}</h5>
                    <p>{{ offer.content }}</p>
                    <span>{{ offer.created_at }}</span>
                </div>
            {% endfor %}-->
            
            <hr/>
        
        </div>
        </div>

        {% endblock %}